---
- hosts: awx_guests
  remote_user: "{{ user_name | default('pi') }}"
  tasks:
    - name: ping test
      ansible.builtin.ping:
      become: yes
      become_method: sudo
      become_user: root
      when: ansible_system == "Linux"
      # when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'RedHat'  or ansible_distribution == 'Rocky'

    - name: Ping windows
      ansible.builtin.win_ping:
      become: yes
      become_method: runas
      become_user: pi
      when: ansible_system == "Win32NT"
      # when: ansible_distribution == 'Windows'
